# Generated by Django 5.1.3 on 2024-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('language', models.CharField(max_length=10, verbose_name='Язык')),
                ('role', models.CharField(max_length=10, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'тг пользователь',
                'verbose_name_plural': 'тг пользователи',
                'db_table': 'tg_users',
            },
        ),
    ]
