# Generated by Django 5.1.3 on 2024-11-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgusers',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя Telegram'),
        ),
    ]
