# Generated by Django 5.1.3 on 2024-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='preview_photo',
            field=models.ImageField(null=True, upload_to='project_preview/', verbose_name='Превью'),
        ),
    ]
