# Generated by Django 5.1.3 on 2024-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_preview_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tags',
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='portfolio.tags', verbose_name='Теги'),
        ),
    ]
