# Generated by Django 5.1.3 on 2024-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projects_tags_projects_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на проект'),
        ),
    ]
